version: "3.9"
services:
  db:
    image: "mysql:5.7"
    volumes:
      - cinemarch-db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
volumes:
  cinemarch-db-data:
