name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false

      - name: Download dependencies
        run: go mod download

      - name: Setup mysql
        run: make run-local-db

      - name: Migration
        run: make migrate

      - name: Run tests
        run: make test

      - name: Build
        run: make build
